services:
  frontend:
    build:
      context: ./
      args:
        VITE_API_BASE_URL: ""
    container_name: club-frontend
    ports:
      - "5173:80"
    networks:
      - club-network

networks:
  club-network:
    external: true
    name: club-network
